// feedlist
export const SET_SEARCHED_SCOOPS = 'SET_SEARCHED_SCOOPS';
export const ADD_MATCH = 'ADD_MATCH';
export const SET_FOUND_MATCHES = 'SET_FOUND_MATCHES';


// auth
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGOUT = 'LOGOUT'
export const GET_TOKEN = 'GET_TOKEN'


// HOME COMPONENTS
//  * feedlist
export const VIEW_PROFILE  = 'VIEW_PROFILE'
export const LOADING_USER  = 'LOADING_USER'


//  * filters
export const UPDATE_FILTER = 'UPDATE_FILTER'
export const UPDATE_SLIDER = 'UPDATE_SLIDER'

export const RESET_FILTER  = 'RESET_FILTER'
export const SAVE_FILTER   = 'SAVE_FILTER'
export const SET_PREV_FILTERS = 'SET_PREV_FILTERS'


// Messenger
export const EDIT_CHATS = 'EDIT_CHATS'
export const CANCEL_EDIT_CHATS = 'CANCEL_EDIT_CHATS'

// Photo Album
export const OPEN_ALBUM = 'OPEN_ALBUM'
export const CLOSE_ALBUM = 'CLOSE_ALBUM'


// personal profile
export const GET_MY_IMAGES = 'GET_MY_IMAGES'
export const SET_MY_IMAGES = 'SET_MY_IMAGES'

export const ADD_ALBUM = 'ADD_ALBUM'
export const ADD_ALBUM_IDS = 'ADD_ALBUM_IDS'
export const ADD_ALBUM_COVER_URL = 'ADD_ALBUM_COVER_URL'
export const GOT_MY_ALBUMS = 'GOT_MY_ALBUMS'
export const IMPORT_PICTURE = 'IMPORT_PICTURE'

export const SET_ALBUM_DETAIL_IMAGES = 'SET_ALBUM_DETAIL_IMAGES'
export const ADD_ALBUM_DETAIL_IMAGES_URL = 'ADD_ALBUM_DETAIL_IMAGES_URL'
export const EXIT_ALBUM_DETAIL ='EXIT_ALBUM_DETAIL'

export const SET_ALBUM_IMAGE_TO_SAVE ='SET_ALBUM_IMAGE_TO_SAVE'
export const SET_IMAGE_URL_TO_SAVE = 'SET_IMAGE_URL_TO_SAVE'
export const SET_IMAGE_URL_TO_PREVIEW = 'SET_IMAGE_URL_TO_PREVIEW'

export const UPDATE_ALBUM_PHOTOS = 'UPDATE_ALBUM_PHOTOS'



export const SET_COVER_PHOTO_IDS = 'SET_COVER_PHOTO_IDS'
export const RESET_ALBUM_IMAGE_PREVIEW = 'RESET_ALBUM_IMAGE_PREVIEW'
export const APPEND_TO_MY_PICTURE_ORDER = 'APPEND_TO_MY_PICTURE_ORDER'
